Fix Issue #287 to address unassigned variable
unclecode/crawl4ai pull request #288
Opened 2024-11-23 19:04 UTC by leonson

I encountered the same problem while trying the [Colab project](https://colab.research.google.com/drive/1SgRPrByQLzjRfwoRNq1wSGE9nYY_EE8C?usp=sharing#scrollTo=003376f3): when execute through the cell "Basic and Simple Crawl" I encountered problem:
```
Pass warning=False to suppress this warning.
  result = await crawler.arun(
Error using new markdown generation strategy: local variable 'filtered_html' referenced before assignment
```
Checked code and apparently yesterday's update [here](https://github.com/unclecode/crawl4ai/blame/0d0cef343842af2aa369423790e159620e717f6c/crawl4ai/markdown_generation_strategy.py#L104) did not consider possible unassigned scenario of `filtered_html`

This fixed the problem. Tested on local and now I can see crawl4ai works on the sample website:
```
Pass warning=False to suppress this warning.
  result = await crawler.arun(
IE 11 is not supported. For an optimal experience visit our site on another browser.

Skip to Content

[NBC News Logo](https://www.nbcnews.com/)

Sponsored By

  * [Politics](https://www.nbcnews.com/politics)
  * [U.S. News](https://www.nbcnews.com/us-news)
  * Local
  * [New York](https://www.nbcnews.com/new-york)
  * [Los Angeles](https://www.nbcnews.com/los-angeles)
  * [Chicago](https://www.nbcnews.com/chicago)
  * [Dallas-Fort Worth](https://www.nbcnews.com/dallas-fort-worth)
  * [Philadelph
```

2024-11-27 07:19 UTC, unclecode requested changes
@leonson thanks for the contribution, and you are actually right, I missed the declaration. If you look at line number 93 there, I define `fit_markdown` variable but I forgot about `filtered_html`. I suggest you add `filtered_html` over there to keep the consistency in the declaration. Please apply the change and update your pull request, then I'll merge it. Thank you so much. Btw, I will add you to our contribution list, and if you're interested, share with me your email address, and I'll send an invitation link to Discord.

2024-11-27 12:15 UTC, unclecode commented
@leonson Actually, I noticed another recent pull request has been merged and covered this issue. However, I am adding your name to our contributor list, and I appreciate the support. If you are interested, please share with me your email address and I will send the Discord invitation.

2024-11-27 12:15 UTC, closed without merging

2024-11-27 16:01 UTC, leonson commented
> @leonson Actually, I noticed another recent pull request has been merged and covered this issue. However, I am adding your name to our contributor list, and I appreciate the support. If you are interested, please share with me your email address and I will send the Discord invitation.

Got it, thanks! Yes saw that PR which covered more so it's better to merge that one. I'll send you an email.

2024-11-28 11:39 UTC, unclecode commented
@leonson Yes, it was very similar to your original idea and covered a few more variables. By the way, I appreciate your support.